version: '3.8'

services:
  app:
    build: . # Memberitahu Docker Compose untuk build dari Dockerfile di direktori ini
    container_name: neverlandstudio_app
    ports:
      - "80:80"
    restart: unless-stopped