server {
    listen 80;
    server_name localhost;

    # Lokasi untuk file statis (React/Vue/Angular build)
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # Meneruskan semua request API ke layanan backend
    location /api {
        proxy_pass http://backend:5000; # 'backend' adalah nama service di docker-compose
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}